-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgp49qUzBaqIGIwVts
qPYN4QtQAvFpSadh5eRrmRr49hegCgYIKoZIzj0DAQehRANCAARhTuENwnf5ncRR
0jaxuQXhAOTJZI4XFIFsogYjdta0CFiJbX3rGhK27EYBeDRC9X3TdBuXsEpwfuSD
kItPBU0Q
-----END PRIVATE KEY-----